version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: students_descomplica
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build: ./server
    depends_on:
      - db
    command: yarn start
    ports:
      - 4000:4000

  web:
    build: ./web
    depends_on:
      - server
    ports:
      - 8080:80
